export const GET_PRODUCTS = "GET_PRODUCTS";
export const SEARCH_PRODUCT_NAME = "SEARCH_PRODUCT_NAME";
export const GET_CATEGORIES = "GET_CATEGORIES"
export const POST_PRODUCT ="POST_PRODUCT"
export const SET_FILTERS ="SET_FILTERS"
export const GET_FILTERED_CATEGORIES = "GET_FILTERED_CATEGORIES";
export const SEND_EMAIL_REQUEST = "SEND_EMAIL_REQUEST"
export const CREATE_CHECKOUT_SESSION = "CREATE_CHECKOUT_SESSION";
export const PAYMENT_SUCCESSFUL = "PAYMENT_SUCCESSFUL";
export const PAYMENT_FAILED = "PAYMENT_FAILED";
export const POST_REVIEW_PRODUCT = "POST_REVIEW_PRODUCT";
export const SEND_NEWSLETTER_REQUEST = 'SEND_NEWSLETTER_REQUEST';
export const SEND_NEWSLETTER_SUCCESS = 'SEND_NEWSLETTER_SUCCESS';
export const SEND_NEWSLETTER_FAILURE = 'SEND_NEWSLETTER_FAILURE';

